// AUTO-GENERATED by scripts/prepare-gallery-images.mjs. Do not edit by hand.
// An empty list means the 3D gallery shows generated placeholder paintings.
export const galleryArtworkPaths: string[] = [
  "/gallery/artworks/artwork-01.jpg",
  "/gallery/artworks/artwork-02.jpg",
  "/gallery/artworks/artwork-03.jpg",
  "/gallery/artworks/artwork-04.jpg",
  "/gallery/artworks/artwork-05.jpg",
  "/gallery/artworks/artwork-06.jpg",
  "/gallery/artworks/artwork-07.jpg",
  "/gallery/artworks/artwork-08.jpg",
  "/gallery/artworks/artwork-09.jpg",
  "/gallery/artworks/artwork-10.jpg",
  "/gallery/artworks/artwork-11.jpg",
  "/gallery/artworks/artwork-12.jpg",
  "/gallery/artworks/artwork-13.jpg"
];
