// AUTO-GENERATED by scripts/prepare-gallery-images.mjs. Do not edit by hand.
// An empty list means the 3D gallery shows generated placeholder paintings.
export const galleryArtworks: { full: string; small: string }[] = [
  {
    "full": "/gallery/artworks/artwork-01.jpg",
    "small": "/gallery/artworks/artwork-01-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-02.jpg",
    "small": "/gallery/artworks/artwork-02-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-03.jpg",
    "small": "/gallery/artworks/artwork-03-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-04.jpg",
    "small": "/gallery/artworks/artwork-04-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-05.jpg",
    "small": "/gallery/artworks/artwork-05-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-06.jpg",
    "small": "/gallery/artworks/artwork-06-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-07.jpg",
    "small": "/gallery/artworks/artwork-07-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-08.jpg",
    "small": "/gallery/artworks/artwork-08-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-09.jpg",
    "small": "/gallery/artworks/artwork-09-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-10.jpg",
    "small": "/gallery/artworks/artwork-10-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-11.jpg",
    "small": "/gallery/artworks/artwork-11-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-12.jpg",
    "small": "/gallery/artworks/artwork-12-m.jpg"
  },
  {
    "full": "/gallery/artworks/artwork-13.jpg",
    "small": "/gallery/artworks/artwork-13-m.jpg"
  }
];
